{
 "title": "My Demo RED",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Latency p95",
   "type": "timeseries",
   "description": "95-й перцентиль затримки запитів.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(http_request_duration_ms_bucket[5m])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "description": "Показує кількість HTTP-запитів за секунду.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(\r\n  rate(http_requests_total[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate (%)",
   "type": "timeseries",
   "description": "Відображає відсоток помилок сервісу.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 *\r\nsum(\r\n  rate(http_requests_error_total[5m])\r\n)\r\n/\r\nsum(\r\n  rate(http_requests_total[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In-flight requests",
   "type": "timeseries",
   "description": "Скільки запитів обробляється прямо зараз.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "http_inflight_requests", "legendFormat": "__auto" }
   ]
  }
 ]
}